//socket events
export const SocketEvent = {
  CONNECTION: "connection",
  DISCONNECT: "disconnect",
  JOIN_ROOM: "join-room",
  LEAVE_ROOM: "leave-room",
  ROOM_JOINED: "room-joined",
  USER_JOINED: "user-joined",
  USER_LEFT: "user-left",
  CODE_CHANGE: "code-change",
  REMOTE_CODE_CHANGE: "remote-code-change",
  CURSOR_CHANGE: "cursor-change",
  INITIAL_CODE: "initial-code",
  REMOTE_CURSOR_CHANGE: "remote-cursor-change",
  SYNC_DOCUMENT: "sync-document",
  ERROR: "error",
  ROOM_STATE: "room-state",
  AWARENESS_UPDATE : "awareness:update",
  REMOTE_AWARENESS_UPDATE : "remote:awareness:update",
};
